### ISSUE TITLE
Pale Moon Add-ons Site?

### ISSUE THREAD

**Issue by Lootyhoof** [InfernoZeus/BarTabTycho#1]
Hey there,

Thanks for this! I was just wondering if you'd be interested in this being hosted on the [Pale Moon Add-ons Site](https://addons.palemoon.org/)? With AMO moving closer to a WebExtensions-only world it's only a matter of time before people will want a BarTab version specifically for Pale Moon...

Hosting there will ensure that users get new updates automatically, as well as having its own listing amongst the many other add-ons currently there. You will get an FTP account to upload new updates directly; there isn't any review period.

There's of course no obligation to do so, though I'm sure many users will be happy to see it there. For full details on what this entails please see [here](https://developer.palemoon.org/Add-ons:Site).

Thanks!

**Comment by InfernoZeus** [comment]
Yes, definitely interested in this! 

When I originally forked this months ago I thought there would be more work needed to actually make it work cleanly work with Pale Moon, but I've been using it ever since with no problems whatsoever. Because of this, the only difference in this forked version is the targetApplication ID. If you think that's worthy enough to have it on the Pale Moon Add-ons site, I'm happy to add it.

**Comment by InfernoZeus** [comment]
Also, I'm intrigued how you found this? :grin:

**Comment by Lootyhoof** [comment]
Great, thanks! 👍

I actually found this because I was poking around GitHub to see where the latest fork of BarTab was at - as it turns out it was yours, and a Pale Moon version at that! It works great too!

Are you OK with me emailing you at the address in your profile? I just need to grab a bit of data to set you up (and send you user details), and then we're good to go.

**Comment by InfernoZeus** [comment]
Yep, that's fine!

**Comment by Lootyhoof** [comment]
Aaand we're live! http://addons.palemoon.org/addon/bartab-tycho/

Thanks!

**Comment by InfernoZeus** [comment]
Thanks for pushing me to do this. Probably would never have got round to it
on my own!

**Comment by Lootyhoof** [comment]
No problem - glad to be of help! :)
