### ISSUE TITLE
Unusual 'chrome' page can't be kept loaded - NewsFox

### ISSUE THREAD

**Issue by OmegaPhil** [InfernoZeus/BarTabTycho#5]
On one of my windows, I have [NewsFox](https://addons.mozilla.org/en-US/firefox/addon/newsfox/) pinned, with 'Keep Pages from newsfox Loaded' - however on every browser startup the tab is not loaded. I assume the 'chrome' site the addon uses is too unusual: chrome://newsfox/content/newsfox.xul

Please could this be supported? Before I realised originally, I lost a load of feed contents as the page wasn't 'running'.

Thanks

Pale Moon 27.7.2

**Comment by spanktastic2120** [comment]
Change the first setting in the addon, "when restoring tabs from a previous session" to "load them"

**Comment by OmegaPhil** [comment]
The tab doesn't load on restart, even when 'Don't load tabs until selected' in Pale Moon is off (normally its on for me). NewsFox has a number in its tab title associated with new feed items available, I'll leave the tab alone and see if that changes at all.

**Comment by OmegaPhil** [comment]
Good news - playing around with the various settings, I have been able to show that the UI is lying - even with 'dont load them' for BarTab's 'When restoring tabs from a previous session' and Pale Moon's 'Dont load tabs until selected', and the tab greyed out, it is still loaded and updating feeds (verifiable via the unread count in the tab title and the icon on the status bar).

The NewsFox 'unloaded tab' and suddenly everything updating when I 'loaded' it spooked me - NewsFox is working fine (Could perhaps be the icon in the status bar that effectively keeps it loaded).
